#!/bin/tcsh

\rm TAPE1 TAPE2 TAPE3 TAPE6 TAPE10

# Set up link to AER line file (e.g. aer_v_3.6) that comes in the AER line parameter database
set line_file = "aer_v_3.6"

# Set up link to LNFL executable
set lnfl_ex = "../../lnfl_v3.1_linux_pgi_sgl"

\rm TAPE5 TAPE1 TAPE3 lnfl

#ln -s $line_file TAPE1
ln -s TAPE5_ex TAPE5
ln -s $lnfl_ex lnfl

time lnfl $line_file

\mv TAPE3 TAPE3_$line_file
\mv TAPE6 TAPE6_$line_file
\mv TAPE7 TAPE7_$line_file

